In [3]:
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns
plt.style.use('ggplot')
%matplotlib inline

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [4]:
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')

In [ ]:
a = train['Unnamed']

In [6]:
train.head().T

,0,1,2,3,4
Unnamed: 0,1,2,3,4,5
NU_INSCRICAO,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,2c3acac4b33ec2b195d77e7c04a2d75727fad723,f4545f8ccb9ff5c8aad7d32951b3f251a26e6568,3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe,bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268
NU_ANO,2016,2016,2016,2016,2016
CO_MUNICIPIO_RESIDENCIA,4314902,2304707,2304400,3304557,1302603
NO_MUNICIPIO_RESIDENCIA,Porto Alegre,Granja,Fortaleza,Rio de Janeiro,Manaus
CO_UF_RESIDENCIA,43,23,23,33,13
SG_UF_RESIDENCIA,RS,CE,CE,RJ,AM
NU_IDADE,24,17,21,25,28
TP_SEXO,M,F,F,F,M
TP_ESTADO_CIVIL,0,0,0,0,0
TP_COR_RACA,1,3,3,0,2
TP_NACIONALIDADE,1,1,1,1,1
CO_MUNICIPIO_NASCIMENTO,4.3149e+06,2.30471e+06,2.3044e+06,3.30456e+06,1.5053e+06
NO_MUNICIPIO_NASCIMENTO,Porto Alegre,Granja,Fortaleza,Rio de Janeiro,Oriximin√°
CO_UF_NASCIMENTO,43,23,23,33,15
SG_UF_NASCIMENTO,RS,CE,CE,RJ,PA
TP_ST_CONCLUSAO,1,2,3,1,1
TP_ANO_CONCLUIU,4,0,0,9,4
TP_ESCOLA,1,2,1,1,1
TP_ENSINO,NaN,1,NaN,NaN,NaN
IN_TREINEIRO,0,0,0,0,0
CO_ESCOLA,NaN,2.30052e+07,NaN,NaN,NaN
CO_MUNICIPIO_ESC,NaN,2.30471e+06,NaN,NaN,NaN
NO_MUNICIPIO_ESC,NaN,Granja,NaN,NaN,NaN
CO_UF_ESC,NaN,23,NaN,NaN,NaN
SG_UF_ESC,NaN,CE,NaN,NaN,NaN
TP_DEPENDENCIA_ADM_ESC,NaN,2,NaN,NaN,NaN
TP_LOCALIZACAO_ESC,NaN,1,NaN,NaN,NaN
TP_SIT_FUNC_ESC,NaN,1,NaN,NaN,NaN
IN_BAIXA_VISAO,0,0,0,0,0
...,...,...,...,...,...
Q021,A,A,A,B,A
Q022,C,A,B,D,B
Q023,A,A,A,B,A
Q024,A,A,A,C,A
Q025,A,A,A,B,A
Q026,C,A,A,C,B
Q027,H,NaN,NaN,F,F
Q028,E,NaN,NaN,C,D
Q029,5,NaN,NaN,2,5
Q030,5,NaN,NaN,0,4
Q031,1,NaN,NaN,5,3
Q032,0,NaN,NaN,5,5
Q033,0,NaN,NaN,5,4
Q034,5,5,5,5,5
Q035,5,5,5,5,5
Q036,0,1,5,5,4
Q037,5,1,5,5,3
Q038,5,1,5,2,1
Q039,5,1,5,5,4
Q040,5,1,5,5,5
Q041,5,NaN,NaN,5,NaN
Q042,A,A,A,C,A
Q043,A,A,A,A,A
Q044,A,C,A,A,A
Q045,A,A,A,A,A
Q046,A,B,C,A,A
Q047,A,A,A,D,A
Q048,A,A,A,A,A
Q049,B,C,B,A,A
Q050,D,A,A,A,A

In [3]:
numeric_features = train.select_dtypes(include=[np.number])
corr = numeric_features.corr()
print (corr['IN_TREINEIRO'].sort_values(ascending=False)[:10], '\n')

IN_TREINEIRO       1.000000
TP_ST_CONCLUSAO    0.533983
TP_PRESENCA_CN     0.094692
TP_PRESENCA_CH     0.094692
TP_PRESENCA_LC     0.092454
TP_PRESENCA_MT     0.092454
Q034               0.055265
Q039               0.040348
Q005               0.033411
Q038               0.018855
Name: IN_TREINEIRO, dtype: float64

In [4]:
features = ['TP_ST_CONCLUSAO', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
                 'TP_PRESENCA_MT']
features_corr = ['IN_TREINEIRO', 'TP_ST_CONCLUSAO', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
                 'TP_PRESENCA_MT']
df_train = train[features_corr]
df_test = test[features]

In [5]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13730 entries, 0 to 13729
Data columns (total 6 columns):
IN_TREINEIRO       13730 non-null int64
TP_ST_CONCLUSAO    13730 non-null int64
TP_PRESENCA_CN     13730 non-null int64
TP_PRESENCA_CH     13730 non-null int64
TP_PRESENCA_LC     13730 non-null int64
TP_PRESENCA_MT     13730 non-null int64
dtypes: int64(6)
memory usage: 643.7 KB

In [6]:
df_train.isnull().sum()

IN_TREINEIRO       0
TP_ST_CONCLUSAO    0
TP_PRESENCA_CN     0
TP_PRESENCA_CH     0
TP_PRESENCA_LC     0
TP_PRESENCA_MT     0
dtype: int64

In [7]:
df_test.isnull().sum()

TP_ST_CONCLUSAO    0
TP_PRESENCA_CN     0
TP_PRESENCA_CH     0
TP_PRESENCA_LC     0
TP_PRESENCA_MT     0
dtype: int64

In [8]:
y_train = df_train['IN_TREINEIRO']
df_train.drop('IN_TREINEIRO', axis=1, inplace=True)
x_train = df_train
x_test = df_test[features]
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

/home/eduardo/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [9]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor( 
           criterion='mae', 
           max_depth=8,
           max_leaf_nodes=None,
           min_impurity_split=None,
           min_samples_leaf=1,
           min_samples_split=2,
           min_weight_fraction_leaf=0.0,
           n_estimators= 500,
           n_jobs=-1,
           random_state=0,
           verbose=0,
           warm_start=False
)

In [10]:
regressor.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=8,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=-1,
                      oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [11]:
x_test = df_test[features] 
x_test = sc.transform(x_test)

In [12]:
y_pred_test = regressor.predict(x_test)
y_pred_train = regressor.predict(x_train)

In [13]:
print('MAE:', metrics.mean_absolute_error(y_train, y_pred_train).round(8)  )
print('MSE:', metrics.mean_squared_error(y_train, y_pred_train).round(8) )  
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_train, y_pred_train)).round(8))

MAE: 0.03812673
MSE: 0.03804982
RMSE: 0.19506363

In [14]:
y_pred_test

array([0., 0., 1., ..., 0., 0., 0.])

In [15]:
type(y_pred_test)

numpy.ndarray

In [16]:
submission = pd.DataFrame()
submission['NU_INSCRICAO'] = test.NU_INSCRICAO
submission['IN_TREINEIRO'] = y_pred_test.astype(int)

In [17]:
submission.sample(20)

                                  NU_INSCRICAO  IN_TREINEIRO
374   73de61ef5ce55a99c860b90cb6ae40cf5204c74a             0
1575  5580681512f1b8ba033fe61b6bdd4741872cade5             0
3081  653828d5ec6455de87fb37922c90d7a38e7a1793             0
3680  3b4b5258e3d42b2c871fceb4b8d1402463d95a7b             0
992   33e3233640c58dd50233b1f6169af36a2cfb7c96             0
3352  64afa113b956ee1085921c7f57fa8d68f9f7367b             0
403   c296cb821061a1c7c717f1f79adaff624c62493f             0
1732  47dc816b33071b369e044dae469016d2d3d04167             0
4512  6ae44e532f63d0009e8011c564bd113a1e15ae0f             0
3894  a3754ee140aaeff6a7f29f27ead573b6e33fb414             0
1281  538087965cf0f0d278235197351ca71f71fd4a0c             0
2753  164df12f8a7544f1fd3ae6e11132a41528bb9e7f             0
1512  2b5df46834f8b43a4590b224b2bb98f8620effb8             1
1967  3532ecacbcf1ff0915f09a0d08712471bc092a66             1
1395  e8eed79d69286f6ed5ebe8c291bd6cb870121d23             0
4535  0b17f2756dbe31681e9a9de9a162a522da14099e             0
232   a3124d236e2b1eb5281f0f388a733d5871f07850             0
2397  5099e54847f4c16ffc824fb88ba96317655bb16e             0
4399  0839eb96fc9a41a5f2bcec0f60333d1395ffce32             0
2664  2056b787eb929274da2da1261d1cc4016642c1e2             0

In [18]:
submission.to_csv('answer.csv', index=False, header=True)