In [1]:
import pandas as pd

In [2]:
port_1 = pd.read_csv("estaticos_portfolio1.csv")
port_2 = pd.read_csv("estaticos_portfolio2.csv")
port_3 = pd.read_csv("estaticos_portfolio3.csv")
mercado = pd.read_csv("estaticos_market.csv")

In [3]:
mercado_df = mercado.copy()

In [4]:
mercado.describe()

,Unnamed: 0,idade_empresa_anos,vl_total_tancagem,vl_total_veiculos_antt,vl_total_veiculos_leves,vl_total_veiculos_pesados,qt_art,vl_total_veiculos_pesados_grupo,vl_total_veiculos_leves_grupo,vl_total_tancagem_grupo,...,media_meses_servicos,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais
count,462298.00000,462298.000000,280.000000,176.000000,30684.000000,30684.000000,6590.000000,460371.000000,460371.000000,1760.000000,...,76261.000000,76261.000000,76261.000000,103574.000000,103574.000000,103574.000000,73888.000000,74014.000000,103574.000000,462298.000000
mean,231148.50000,9.948677,32.014286,3.818182,2.244329,1.177813,5.769044,3.591801,48.699177,134.597159,...,58.060498,96.661983,36.258851,12.324570,12.178529,14.343329,3.097607,-5.834288,9.510699,28.737044
std,133454.08171,9.615664,81.280168,6.797555,9.572536,6.589059,25.450950,72.600352,1206.696804,683.774506,...,142.951278,279.541243,123.411370,222.456579,222.584458,239.885359,163.581549,443.825819,27.918737,468.626094
min,0.00000,0.016438,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,1.933333,1.933333,1.933333,0.000000,0.000000,0.000000,-100.000000,-100.000000,0.000000,0.000000
25%,115574.25000,2.756164,15.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,15.000000,...,25.203704,33.333333,6.966667,0.000000,0.000000,0.000000,0.000000,-44.444444,0.000000,0.000000
50%,231148.50000,6.704110,15.000000,2.000000,1.000000,0.000000,2.000000,0.000000,0.000000,15.000000,...,43.533333,61.766667,23.200000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000
75%,346722.75000,14.465753,30.000000,4.000000,2.000000,1.000000,4.000000,0.000000,0.000000,66.250000,...,68.883333,96.266667,46.500000,5.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000
max,462297.00000,106.432877,1215.000000,50.000000,489.000000,363.000000,1017.000000,9782.000000,122090.000000,11922.000000,...,5099.066667,5099.066667,5099.066667,51547.000000,51547.000000,54205.000000,27800.000000,87300.000000,1400.000000,9647.000000

In [6]:
mercado_df.shape

(462298, 182)

In [27]:
def filterColumns(columnName):
    return [bla for bla in mercado_df.columns if columnName in bla ]

In [30]:
filteredColumns = filterColumns('socio')
filteredColumns.remove('qt_socios')
filteredColumns

['qt_socios_pf',
 'qt_socios_pj',
 'idade_media_socios',
 'idade_maxima_socios',
 'idade_minima_socios',
 'qt_socios_st_regular',
 'qt_socios_st_suspensa',
 'qt_socios_masculino',
 'qt_socios_feminino',
 'qt_socios_pep',
 'qt_alteracao_socio_total',
 'qt_alteracao_socio_90d',
 'qt_alteracao_socio_180d',
 'qt_alteracao_socio_365d',
 'qt_socios_pj_ativos',
 'qt_socios_pj_nulos',
 'qt_socios_pj_baixados',
 'qt_socios_pj_suspensos',
 'qt_socios_pj_inaptos',
 'vl_idade_media_socios_pj',
 'vl_idade_maxima_socios_pj',
 'vl_idade_minima_socios_pj',
 'qt_socios_coligados']

In [31]:
#As colunas de socios possuáº½m vÃ¡rias repetiÃ§Ãµes.
#Manteremos apena a quantidade de sÃ³cios e desconsideraremos as outras
mercado_drop = mercado_df.drop(filteredColumns, axis=1)

MemoryError: Unable to allocate array with shape (121, 462298) and data type float64

In [16]:
mercado_df.shape

(462298, 182)