# Aplicando o Merge nas bases de dados

In [1]:
#Importando pacotes
import pandas as pd

## Leitura dos arquivos

In [2]:
df_portifolio_1 = pd.read_csv('../data/estaticos_portfolio1.csv')

In [3]:
df_portifolio_2 = pd.read_csv('../data/estaticos_portfolio2.csv')

In [4]:
df_portifolio_3 = pd.read_csv('../data/estaticos_portfolio3.csv')

In [ ]:
df_market = pd.read_csv('../data/estaticos_market.csv')

In [30]:
df_merge_port_2 = df_market.merge(df_portifolio_2, on='id', how='inner')

In [31]:
df_merge_port_3 = df_market.merge(df_portifolio_3, on='id', how='inner')

In [41]:
df_merge_port_2.to_csv('../data/estaticos_portfolio2_merge.csv', index=False)

In [42]:
df_merge_port_3.to_csv('../data/estaticos_portfolio3_merge.csv', index=False)

In [46]:
df_merge_2 = pd.read_csv('../data/estaticos_portfolio2_merge.csv')
df_merge_2 = df_merge_2.drop(columns='Unnamed: 0_x')

In [47]:
df_merge_2.head()

,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,fl_me,...,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais,Unnamed: 0_y
0,09e95c1a84049001d086470a8f320a19b076f955a89122...,True,AUTARQUIA ESTADUAL OU DO DISTRITO FEDERAL,AC,ADMINISTRACAO PUBLICA,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,11.243836,10 a 15,False,...,357.066667,25.533333,1361.0,1361.0,1383.0,0.000000,-1.590745,0.000000,0,0
1,dc9d155f5bcd3172031e2ec9431786e8871ff4b0ff4728...,True,MUNICIPIO,RN,OUTROS,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,43.789041,> 20,False,...,526.133333,23.200000,991.0,991.0,1306.0,0.000000,-24.119449,0.000000,0,1
2,16843c9ffb920170477118933798510d8d5f00f5c56c12...,True,SOCIEDADE SIMPLES LIMITADA,PI,ENTIDADES EMPRESARIAIS,SERVICOS DE EDUCACAO,SERVIÇO,16.389041,15 a 20,False,...,149.033333,4.866667,119.0,104.0,113.0,14.423077,5.309735,6.250000,0,2
3,ff045934d90aab184dd15e66daf3b3c97193bda5449298...,True,MUNICIPIO,AM,OUTROS,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,39.671233,> 20,False,...,555.766667,28.300000,1829.0,1829.0,1875.0,0.000000,-2.453333,0.000000,1,3
4,a0ce528caab2c62497a548d0ebd9e935143ef81ed7dbf0...,True,SOCIEDADE EMPRESARIA LIMITADA,RN,ENTIDADES EMPRESARIAIS,PRODUTOS DE AGROPECUARIA,AGROPECUARIA,20.268493,> 20,False,...,134.833333,2.933333,177.0,130.0,120.0,36.153846,47.500000,41.042345,0,4

In [48]:
df_merge_3 = pd.read_csv('../data/estaticos_portfolio3_merge.csv')
df_merge_3 = df_merge_3.drop(columns='Unnamed: 0_x')

In [49]:
df_merge_3.head()

,id,fl_matriz,de_natureza_juridica,sg_uf,natureza_juridica_macro,de_ramo,setor,idade_empresa_anos,idade_emp_cat,fl_me,...,max_meses_servicos,min_meses_servicos,qt_funcionarios,qt_funcionarios_12meses,qt_funcionarios_24meses,tx_crescimento_12meses,tx_crescimento_24meses,tx_rotatividade,qt_filiais,Unnamed: 0_y
0,bb61c09449a1c1f8b78955d8b7a7f73599e78358993fe2...,True,MUNICIPIO,MA,OUTROS,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,21.813699,> 20,False,...,259.166667,40.500000,745.0,745.0,745.0,0.000000,0.000000,0.00,2,0
1,16843c9ffb920170477118933798510d8d5f00f5c56c12...,True,SOCIEDADE SIMPLES LIMITADA,PI,ENTIDADES EMPRESARIAIS,SERVICOS DE EDUCACAO,SERVIÇO,16.389041,15 a 20,False,...,149.033333,4.866667,119.0,104.0,113.0,14.423077,5.309735,6.25,0,1
2,1b8d092daff12bed8b3c2ab93bf5df2921865a68aca185...,True,ORGAO PUBLICO DO PODER EXECUTIVO ESTADUAL OU D...,AM,ADMINISTRACAO PUBLICA,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,40.380822,> 20,False,...,557.866667,24.200000,170.0,170.0,177.0,0.000000,-3.954802,0.00,0,2
3,3aafa3a1f12f483740a52956af100223333d0e3c79bf2c...,True,MUNICIPIO,PI,OUTROS,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,43.854795,> 20,False,...,506.966667,31.333333,151.0,151.0,151.0,0.000000,0.000000,0.00,0,3
4,c60431fbca90067f105570e1e8a684bcd7048205bbf6c4...,True,MUNICIPIO,RN,OUTROS,"ADMINISTRACAO PUBLICA, DEFESA E SEGURIDADE SOCIAL",SERVIÇO,43.865753,> 20,False,...,556.833333,34.033333,229.0,229.0,418.0,0.000000,-45.215311,0.00,1,4